#ifndef UI_ANCHOR_MODES
#define UI_ANCHOR_MODES

#define UI_ANCHOR_MODE_TOP_LEFT 0
#define UI_ANCHOR_MODE_TOP 1
#define UI_ANCHOR_MODE_TOP_RIGHT 2
#define UI_ANCHOR_MODE_RIGHT 3
#define UI_ANCHOR_MODE_BUTTOM_RIGHT 4
#define UI_ANCHOR_MODE_BUTTOM 5
#define UI_ANCHOR_MODE_BUTTOM_LEFT 6
#define UI_ANCHOR_MODE_LEFT 7
#define UI_ANCHOR_MODE_CENTER 8
#define UI_ANCHOR_MODE_FILL 9
#define UI_ANCHOR_MODE_TOP_FILL 10
#define UI_ANCHOR_MODE_RIGHT_FILL 11
#define UI_ANCHOR_MODE_BUTTOM_FILL 12
#define UI_ANCHOR_MODE_LEFT_FILL 13

#endif